# Data Set Description

### In this assignment, I use the Titanic data set, the training set and test set is split. However, since there is no target value in test set, we will using 2/3 for train and 1/3 for test. This data set is with ten features which are lists as below and the trget is survival,

Variable	Definition	Key

survival	Survival	0 = No, 1 = Yes

pclass	Ticket class	1 = 1st, 2 = 2nd, 3 = 3rd

sex	Sex	

Age	Age in years	

sibsp	# of siblings / spouses aboard the Titanic	

parch	# of parents / children aboard the Titanic	

ticket	Ticket number	

fare	Passenger fare	

cabin	Cabin number	

embarked	Port of Embarkation	C = Cherbourg, Q = Queenstown, S = Southampton

### we will discard the id features since each object has a unique value

# Load the Data Set

In [375]:
import pandas as pd
import numpy as np
k = pd.read_csv('data.csv')
Target = k.Survived;
Tar = np.array(Target)
print(k)

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch      Fare  \
0              1         0       3    male  22.0      1      0    7.2500   
1              2         1       1  female  38.0      1      0   71.2833   
2              3         1       3  female  26.0      0      0    7.9250   
3              4         1       1  female  35.0      1      0   53.1000   
4              5         0       3    male  35.0      0      0    8.0500   
5              6         0       3    male   NaN      0      0    8.4583   
6              7         0       1    male  54.0      0      0   51.8625   
7              8         0       3    male   2.0      3      1   21.0750   
8              9         1       3  female  27.0      0      2   11.1333   
9             10         1       2  female  14.0      1      0   30.0708   
10            11         1       3  female   4.0      1      1   16.7000   
11            12         1       1  female  58.0      0      0   26.5500   
12          

# Binarize the Data

## Target - Survived

In [376]:
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
lb = preprocessing.LabelBinarizer()
Survived = lb.fit_transform(Target)
k.Survived = Survived

### Sex

In [377]:
Sex = lb.fit_transform(k.Sex)
k.Sex = Sex
enc = OneHotEncoder()
Sex = enc.fit_transform(Sex).toarray()
print(Sex)

[[ 0.  1.]
 [ 1.  0.]
 [ 1.  0.]
 ..., 
 [ 1.  0.]
 [ 0.  1.]
 [ 0.  1.]]


## Embarked

In [378]:
Emb = le.fit_transform(k.Embarked).reshape(*k.Embarked.shape,1)
k.Embarked = Emb
enc = OneHotEncoder()
Embb = enc.fit_transform(Emb).toarray()
print(Embb)

[[ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 ..., 
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]


## Age

In [379]:
mean_age = np.mean(k.Age)
print('mean_age:',mean_age)
Ageb = k.Age > mean_age
lb = preprocessing.LabelBinarizer()
Age = lb.fit_transform(Ageb)
k.Age = Age
enc = OneHotEncoder()
Ageb = enc.fit_transform(Age).toarray()
print(Ageb)

mean_age: 29.64209269662921
[[ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 ..., 
 [ 1.  0.]
 [ 1.  0.]
 [ 0.  1.]]


## Fare

In [380]:
mean_fare = np.mean(k.Fare)
print('mean_fare:',mean_fare)
Fare = k.Fare > mean_fare
lb = preprocessing.LabelBinarizer()
Fare = lb.fit_transform(Fare)
k.Fare = Fare 
enc = OneHotEncoder()
Fare = enc.fit_transform(Fare).toarray()
print(Fare)

mean_fare: 32.09668087739029
[[ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 ..., 
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]]


### Pclass

In [381]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
Pclass = np.array(k.Pclass).reshape(*k.Pclass.shape,1)
k.Pclass = Pclass
Pclass = enc.fit_transform(Pclass).toarray()
print(Pclass)
#Sex  Age  SibSp  Parch  Fare  Embarked

[[ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 ..., 
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]


### SibSp

In [382]:
SibSp = np.array(k.SibSp).reshape(*k.SibSp.shape,1)
k.SibSp = SibSp
SibSp = enc.fit_transform(SibSp).toarray()
print(SibSp)
len(SibSp[0,:])

[[ 0.  1.  0. ...,  0.  0.  0.]
 [ 0.  1.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  1.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]]


7

### Parch

In [383]:
Parch = np.array(k.Parch).reshape(*k.Parch.shape,1)
k.Parch = Parch
Parch = enc.fit_transform(Parch).toarray()
print(Parch)
len(Parch[0,:])

[[ 1.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  1. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]
 [ 1.  0.  0. ...,  0.  0.  0.]]


7

In [384]:
print('Pclass:{1,2,3}  Sex:{Female,Male}  Age{<=29.64, >29.64}  SibSp:{0,1,2,3,4,5,8}  Parch:{0,1,2,3,4,5,6}  Fare:{<=32.10,>32.10}  Embarked:{C,Q,S}')
print('3bits+2bits+2bits+7bits+7bits+2bits+3bits')
#X =Pclass
#X.Parch = Parch
#X.SibSp = SibSp
#X.Age = Ageb
#X.Sex = Sex
#X.Embarked = Embb

Pclass:{1,2,3}  Sex:{Female,Male}  Age{<=29.64, >29.64}  SibSp:{0,1,2,3,4,5,8}  Parch:{0,1,2,3,4,5,6}  Fare:{<=32.10,>32.10}  Embarked:{C,Q,S}
3bits+2bits+2bits+7bits+7bits+2bits+3bits


In [385]:
Data = k.loc[:,'Pclass':'Embarked']
X = np.array(Data)
X = enc.fit_transform(X).toarray()
Y = np.array(k.Survived)

In [386]:
size_t = int(2*len(X) * 1/3)
x_train = X[0:size_t]
y_train = Y[0:size_t]
x_test = X[size_t+1:]
y_test = Y[size_t+1:]

# Train a BernouilliNB classifier 

In [387]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(x_train, y_train)
BernoulliNB(alpha=1.0, class_prior=None, fit_prior=True)
pr = clf.predict_proba(x_test)
feature_neg = clf.feature_log_prob_[0]
print('feature_neg:',feature_neg)
feature_pos = clf.feature_log_prob_[1]
print('feature_pos:',feature_pos)

feature_neg: [-1.7945334  -1.76174357 -0.40823903 -1.86352627 -0.16856618 -0.42081782
 -1.06859639 -0.33980187 -1.71449069 -3.3239286  -3.58629287 -3.49098269
 -4.27944005 -4.27944005 -0.21555469 -2.2512918  -2.59304109 -5.19573078
 -4.27944005 -5.19573078 -5.88887796 -0.17845094 -1.81134051 -1.86352627
 -2.52158213 -0.26486045]
feature_pos: [-1.01693426 -1.31645079 -0.9822487  -0.34759773 -1.22547901 -0.48977221
 -0.94872601 -0.48977221 -1.11578009 -3.26236094 -4.07329115 -4.07329115
 -5.45958551 -5.45958551 -0.36583531 -1.82199935 -1.96307795 -4.76643833
 -5.45958551 -4.76643833 -5.45958551 -0.40333971 -1.10287669 -1.34871165
 -2.20148898 -0.45563921]


In [388]:
pr = pr.reshape(*pr.shape,1)
pr_neg = pr[:,0]
pr_pos = pr[:,1]

###  In the  following five cases, print the following results: 
#### a) the total positive log-evidence,  b) the total negative log-evidence, c) probability distribution, d) top 3 features values that contribute most to the positive evidence, e) top 3 feature values that contribute the most to the negative evidence

## 1.The most positive object with respect to the probabilities.

In [389]:
print('Pclass:{1,2,3}  Sex:{Female,Male}  Age{<=29.64, >29.64}  SibSp:{0,1,2,3,4,5,8}  Parch:{0,1,2,3,4,5,6}  Fare:{<=32.10,>32.10}  Embarked:{C,Q,S}')
print('3bits+2bits+2bits+7bits+7bits+2bits+3bits')

Pclass:{1,2,3}  Sex:{Female,Male}  Age{<=29.64, >29.64}  SibSp:{0,1,2,3,4,5,8}  Parch:{0,1,2,3,4,5,6}  Fare:{<=32.10,>32.10}  Embarked:{C,Q,S}
3bits+2bits+2bits+7bits+7bits+2bits+3bits


In [390]:
ratio = pr_neg/pr_pos
ind1 =  np.argmax(pr_pos)
print('index of most postive object w.r.t probabilities:',ind1)
obj = x_test[ind1]
print('object:',obj)
pf = feature_pos - feature_neg
P_f = np.multiply(pf,obj)
pff = [i for i in P_f if i>0]
print('the total positive log-evidence:',np.sum(pff))

nf = feature_neg - feature_pos
print(nf)
N_f = np.multiply(nf,obj)
print(N_f)
nff = [i for i in N_f if i>0]
print('the total negtive log-evidence:',np.sum(nff))
print('probability distribution:',pr_pos[ind1],pr_neg[ind1])

index of most postive object w.r.t probabilities: 240
object: [ 1.  0.  0.  1.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.
  0.  0.  0.  0.  1.  1.  0.  0.]
the total positive log-evidence: 4.6646795503
[-0.77759914 -0.44529279  0.57400966 -1.51592854  1.05691283  0.0689544
 -0.11987039  0.14997034 -0.5987106  -0.06156766  0.48699829  0.58230847
  1.18014547  1.18014547  0.15028062 -0.42929244 -0.62996314 -0.42929244
  1.18014547 -0.42929244 -0.42929244  0.22488877 -0.70846383 -0.51481462
 -0.32009315  0.19077876]
[-0.77759914 -0.          0.         -1.51592854  0.          0.
 -0.11987039  0.         -0.5987106  -0.          0.          0.          0.
  0.          0.         -0.42929244 -0.         -0.          0.         -0.
 -0.          0.         -0.70846383 -0.51481462 -0.          0.        ]
the total negtive log-evidence: 0.0
probability distribution: [ 0.9997308] [ 0.0002692]


In [391]:
#print(P_f)
print('top postive features:',np.max(P_f[0:2]),np.max(P_f[3:4]),np.max(P_f[5:6]),np.max(P_f[7:13]),np.max(P_f[14:20]),np.max(P_f[21:22]),np.max(P_f[23:25]))
print('top 3 features: Pclass,Sex,Fares')
#print(N_f)
print('top negtive features:',np.max(N_f[0:2]),np.max(N_f[3:4]),np.max(N_f[5:6]),np.max(N_f[7:13]),np.max(N_f[14:20]),np.max(N_f[21:22]),np.max(N_f[23:25]))
print('top 3 negtive features:NaN')

top postive features: 0.777599138457 1.51592854181 -0.0 0.598710596147 0.429292444189 -0.0 0.514814617627
top 3 features: Pclass,Sex,Fares
top negtive features: -0.0 -1.51592854181 0.0 0.0 0.0 0.0 -0.0
top 3 negtive features:NaN


## 2.The most negative object with respect to the probabilities.

In [392]:
ind =  np.argmax(pr_neg)
print('index of most negtive object w.r.t probabilities:',ind)
obj = x_test[ind]
print('object:',obj)
pf = feature_pos - feature_neg
P_f = np.multiply(pf,obj)
pff = [i for i in P_f if i>0]
print('the total positive log-evidence:',np.sum(pff))

nf = feature_neg - feature_pos
N_f = np.multiply(nf,obj)
nff = [i for i in N_f if i>0]
print('the total negtive log-evidence:',np.sum(nff))
print('probability distribution:',pr_pos[ind],pr_neg[ind])

index of most negtive object w.r.t probabilities: 7
object: [ 0.  0.  1.  0.  1.  1.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  0.  1.  0.  0.  0.  1.]
the total positive log-evidence: 0.0
the total negtive log-evidence: 2.41579537706
probability distribution: [ 0.0063783] [ 0.9936217]


In [393]:
#print(P_f)
print('top postive features:',np.max(P_f[0:2]),np.max(P_f[3:4]),np.max(P_f[5:6]),np.max(P_f[7:13]),np.max(P_f[14:20]),np.max(P_f[21:22]),np.max(P_f[23:25]))
print('top 3 features: NaN')
#print(N_f)
print('top negtive features:',np.max(N_f[0:2]),np.max(N_f[3:4]),np.max(N_f[5:6]),np.max(N_f[7:13]),np.max(N_f[14:20]),np.max(N_f[21:22]),np.max(N_f[23:25]))
print('top 3 negtive features:SibSp,Parch,Fare')

top postive features: 0.0 0.0 -0.0689543973704 0.0 0.0 -0.224888767838 0.0
top 3 features: NaN
top negtive features: -0.0 -0.0 0.0689543973704 0.14997034113 0.150280622176 0.224888767838 -0.0
top 3 negtive features:SibSp,Parch,Fare


## 3.The object that has the largest positive evidence

In [394]:
pf = feature_pos - feature_neg
P_fs = np.multiply(pf,x_test)
lar_pos = []
for i in P_fs:
    pff = [j for j in i if j>0]
    lar_pos.append(np.sum(pff))
ind = np.argmax(lar_pos)
print('Index of the object w.r.t the largest positive evidence:',ind)
print('The value of Log-evidence:',lar_pos[ind])
print('The analysis of (a)-(e)is as above, we will skip the other part')
#print('the total positive log-evidence:',np.sum(pff))

Index of the object w.r.t the largest positive evidence: 240
The value of Log-evidence: 4.6646795503
The analysis of (a)-(e)is as above, we will skip the other part


## 4.The object that has the largest (in magnitude) negative evidence

In [395]:
nf = feature_neg - feature_pos
N_fs = np.multiply(nf,x_test)
lar_neg = []
for i in N_fs:
    nff = [j for j in i if j>0]
    lar_neg.append(np.sum(nff))
ind = np.argmax(lar_neg)
print('Index of the object w.r.t the largest negtive evidence:',ind)
print('The value of Log-evidence:',lar_neg[ind])
obj = x_test[ind]
print('object:',obj)
pf = feature_pos - feature_neg
P_f = np.multiply(pf,obj)
pff = [i for i in P_f if i>0]
print('the total positive log-evidence:',np.sum(pff))

nf = feature_neg - feature_pos
N_f = np.multiply(nf,obj)
nff = [i for i in N_f if i>0]
print('the total negtive log-evidence:',np.sum(nff))
print('probability distribution:',pr_pos[ind],pr_neg[ind])

Index of the object w.r.t the largest negtive evidence: 89
The value of Log-evidence: 3.07080111417
object: [ 0.  0.  1.  0.  1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.  0.
  0.  0.  0.  0.  1.  0.  0.  1.]
the total positive log-evidence: 1.33842696662
the total negtive log-evidence: 3.07080111417
probability distribution: [ 0.06820731] [ 0.93179269]


In [396]:
#print(P_f)
print('top postive features:',np.max(P_f[0:2]),np.max(P_f[3:4]),np.max(P_f[5:6]),np.max(P_f[7:13]),np.max(P_f[14:20]),np.max(P_f[21:22]),np.max(P_f[23:25]))
print('top 3 features: Parch and NaN')
#print(N_f)
print('top negtive features:',np.max(N_f[0:2]),np.max(N_f[3:4]),np.max(N_f[5:6]),np.max(N_f[7:13]),np.max(N_f[14:20]),np.max(N_f[21:22]),np.max(N_f[23:25]))
print('top 3 negtive features:Age, SibSb, and NaN')

top postive features: 0.0 0.0 -0.0689543973704 -0.0 0.629963139651 -0.0 0.0
top 3 features: Parch and NaN
top negtive features: -0.0 -0.0 0.0689543973704 1.18014546825 0.0 0.0 -0.0
top 3 negtive features:Age, SibSb, and NaN


## 5.The most uncertain object (the probabilities are closest to 0.5) 

In [397]:
ind =  np.argmin(np.abs(pr_pos-0.5))
print('index of most unvertain object w.r.t probabilities:',ind)
obj = x_test[ind]
print('object:',obj)
pf = feature_pos - feature_neg
P_f = np.multiply(pf,obj)
pff = [i for i in P_f if i>0]
print('the total positive log-evidence:',np.sum(pff))

nf = feature_neg - feature_pos
N_f = np.multiply(nf,obj)
nff = [i for i in N_f if i>0]
print('the total negtive log-evidence:',np.sum(nff))
print('probability distribution:',pr_pos[ind],pr_neg[ind])

index of most unvertain object w.r.t probabilities: 66
object: [ 1.  0.  0.  0.  1.  0.  1.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  0.  0.  1.  0.  0.  1.]
the total positive log-evidence: 1.66750101459
the total negtive log-evidence: 1.39797220605
probability distribution: [ 0.48707783] [ 0.51292217]


In [398]:
#print(P_f)
print('top postive features:',np.max(P_f[0:2]),np.max(P_f[3:4]),np.max(P_f[5:6]),np.max(P_f[7:13]),np.max(P_f[14:20]),np.max(P_f[21:22]),np.max(P_f[23:25]))
print('top 3 features: Pclass, SibSp,NaN')
#print(N_f)
print('top negtive features:',np.max(N_f[0:2]),np.max(N_f[3:4]),np.max(N_f[5:6]),np.max(N_f[7:13]),np.max(N_f[14:20]),np.max(N_f[21:22]),np.max(N_f[23:25]))
print('top 3 negtive features:Parch, NaN')

top postive features: 0.777599138457 0.0 -0.0 0.0615676640634 0.0 -0.0 0.0
top 3 features: Pclass, SibSp,NaN
top negtive features: -0.0 -0.0 0.0 0.0 0.150280622176 0.0 -0.0
top 3 negtive features:Parch, NaN
